#define USERNAME_LENGTH 32
#define HOSTNAME_LENGTH 32
#define PASSWORD_LENGTH 32
#define REALM_LENGTH 8
#define TARGET_LENGTH 32
#define TIME_THRESHOLD_SECONDS 10
#define DEFAULT_TICKET_LIFE_SECONDS 600
